$schema: https://autonox.ai/schemas/silver/flow-import.v1.schema.json
kind: flow.import.v1
metadata:
  name: mock-hr
spec:
  lifecycle:
    source_type: hard_delete
    sanity_checks:
      max_deletion_rate: 1.0
      min_entities_threshold: 1
  mapper:
    mappings:
      - raw_object_type: mock_hr_identity_link
        canonical_entity: identity_source_link
        spec:
          partitions:
            columns:
              source_key: root.source_key
              source:
                pipe:
                  - const: mock_hr
              object_type: root.object_type
              status:
                pipe:
                  - const: active
            attributes:
              employee_id: root.employee_id
              username: root.username
              first_name: root.first_name
              last_name: root.last_name
              email: root.email
              department: root.department
              job_title: root.job_title
        provenance:
          content_hash_attributes: [source_key]
