specs:
  - kind: materialize.warehouse.v1
    name: mock-hr
    scope: default
    uri: file://${CONFIG_DIR}/materialize.warehouse.yaml
    schema_id: https://autonox.ai/schemas/reconciliation/materialize.warehouse.v1.schema.json
