#!/usr/bin/env bash
# Emits an images.env pinning the three AutoNox workload images by digest.
#
#   ./resolve-digests.sh                        # print to stdout
#   ./resolve-digests.sh --out /etc/autonox/images.env
#   ./resolve-digests.sh --from-lock /media/bundle/bundle.lock
#
# import.sh refuses any image that is not pinned by digest, but manifest.txt
# pins tags — every environment upgrades on its own cadence, and a tag is what a
# human can read. Something has to bridge the two, and until now nothing did
# outside the testkit.
#
# Two sources, because a connected host and an air-gapped one cannot use the
# same one:
#
#   default      ask the container runtime for RepoDigests, pulling if needed.
#   --from-lock  read column 3 of a bundle.lock. Images restored from a
#                `docker save` tar carry NO RepoDigests — the registry digest
#                does not survive the round trip — so on an air-gapped host the
#                lock written by pull-and-save.sh is the only record of them.
#
# The warehouse image is emitted twice: workloads/warehouse reads WAREHOUSE_IMAGE
# and workloads/import reads WAREHOUSE_IMG (TODO.md 6c). One value, two names,
# so there is still only one place to change it.

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="${SCRIPT_DIR}/manifest.txt"
CONTAINER_RUNTIME="${CONTAINER_RUNTIME:-docker}"
PLATFORM="${PLATFORM:-linux/amd64}"

LOCK=""
OUT=""

die() { printf 'ERROR: %s\n' "$*" >&2; exit 2; }

usage() {
  sed -n '2,28p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --from-lock) LOCK="${2:-}"; [[ -n "$LOCK" ]] || die "--from-lock needs a path"; shift 2 ;;
    --out)       OUT="${2:-}";  [[ -n "$OUT"  ]] || die "--out needs a path";       shift 2 ;;
    -h|--help)   usage; exit 0 ;;
    *)           die "unexpected argument: $1" ;;
  esac
done

[[ -f "$MANIFEST" ]] || die "manifest not found: $MANIFEST"
[[ -z "$LOCK" || -f "$LOCK" ]] || die "bundle lock not found: $LOCK"

# Prefix in manifest.txt -> variable names it populates.
names_for() {
  case "$1" in
    collectors)        printf 'COLLECTOR_IMG' ;;
    autonox-warehouse) printf 'WAREHOUSE_IMG WAREHOUSE_IMAGE' ;;
    reconciliation)    printf 'RECONCILE_IMG' ;;
  esac
}

tag_for() {
  local repo="$1"
  awk -v re="^ghcr\\.io/autonox-ai/${repo}:" '$0 ~ re { print; exit }' "$MANIFEST"
}

# Reads the digest from the lock rather than the runtime. Column 3 is a full
# repo@sha256:... reference, or "-" when pull-and-save could not resolve one.
digest_from_lock() {
  local tag="$1" digest
  digest="$(awk -F'\t' -v want="$tag" '$1 == want { print $3; exit }' "$LOCK")"
  [[ -n "$digest" ]] || die "not in $LOCK: $tag (was the bundle built from this manifest.txt?)"
  [[ "$digest" != "-" ]] || die "bundle.lock has no digest for $tag; rebuild the bundle with pull-and-save.sh"
  printf '%s' "$digest"
}

digest_from_runtime() {
  local tag="$1" digest
  if ! "$CONTAINER_RUNTIME" image inspect "$tag" >/dev/null 2>&1; then
    printf 'pull  %s\n' "$tag" >&2
    "$CONTAINER_RUNTIME" pull --platform "$PLATFORM" "$tag" >/dev/null \
      || die "cannot pull $tag; on an air-gapped host use --from-lock"
  fi
  digest="$("$CONTAINER_RUNTIME" image inspect \
    --format '{{if .RepoDigests}}{{index .RepoDigests 0}}{{end}}' "$tag" 2>/dev/null || true)"
  if [[ -z "$digest" ]]; then
    die "$tag has no registry digest — it was loaded from a tar. Use --from-lock <bundle.lock>."
  fi
  printf '%s' "$digest"
}

emit() {
  printf '# Generated by images/resolve-digests.sh from %s\n' "$(basename "$MANIFEST")"
  [[ -n "$LOCK" ]] && printf '# Digests taken from %s\n' "$LOCK"
  printf '#\n# Regenerate after every manifest.txt change. import.sh rejects tags,\n'
  printf '# so a stale digest here is caught; a stale TAG would not be.\n\n'

  local repo tag digest name
  for repo in collectors autonox-warehouse reconciliation; do
    tag="$(tag_for "$repo")"
    [[ -n "$tag" ]] || die "no ghcr.io/autonox-ai/${repo}: entry in $MANIFEST"
    # `|| exit` is load-bearing. set -e does not propagate an exit out of a
    # command substitution nested inside another one, and emit itself runs
    # inside `$(...)` below — without this, a die() here is swallowed and the
    # script happily writes a truncated file and reports success.
    if [[ -n "$LOCK" ]]; then
      digest="$(digest_from_lock "$tag")" || exit $?
    else
      digest="$(digest_from_runtime "$tag")" || exit $?
    fi
    printf '# %s\n' "$tag"
    for name in $(names_for "$repo"); do printf '%s=%s\n' "$name" "$digest"; done
    printf '\n'
  done
}

# Resolve everything before writing a byte. A partial images.env is worse than
# none: `./resolve-digests.sh > images.env` would otherwise leave a truncated
# file behind on failure, and the missing image only surfaces later as an unset
# variable inside import.sh.
output="$(emit)" || exit $?

if [[ -n "$OUT" ]]; then
  tmp="${OUT}.tmp.$$"
  printf '%s\n' "$output" >"$tmp"
  mv "$tmp" "$OUT"
  printf 'wrote %s\n' "$OUT" >&2
else
  printf '%s\n' "$output"
fi
