#!/usr/bin/env bash
# Pull every image listed in images/manifest.txt and save each to a .tar file
# in the output directory. Run this on a host with internet access; ship the
# resulting directory to the air-gapped target by your customer's approved
# transfer method (SFTP, USB, approved share, etc.).
#
# The output directory is a self-describing bundle: alongside the tars it gets
# a bundle.lock recording the manifest entry, resolved image ID, and registry
# digest for each image. load.sh consumes that lock, so a bundle can only load
# what this script actually saved.
#
# Usage:
#   bash images/airgap/pull-and-save.sh <output-dir> [linux/amd64]
#
# The output directory is required and must be outside this repository: bundles
# are large, and the repo is a vendor tree that gets replaced on upgrade.
#
# Auth:
#   For private ghcr.io/autonox-ai images, either run `gh auth login` first or
#   set GHCR_USER and GHCR_TOKEN. Set GHCR_LOGIN=0 to skip this login step.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="${MANIFEST:-${SCRIPT_DIR}/../manifest.txt}"
OUT_DIR="${1:-}"
if [[ -z "$OUT_DIR" ]]; then
  echo "usage: bash images/airgap/pull-and-save.sh <output-dir> [platform]" >&2
  echo "the output directory is required; keep bundles outside this repository" >&2
  exit 2
fi
PLATFORM="${2:-linux/amd64}"
LOCK="${OUT_DIR}/bundle.lock"

if [[ ! -f "$MANIFEST" ]]; then
  echo "manifest not found: $MANIFEST" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

if [[ "${GHCR_LOGIN:-1}" != "0" ]] && grep -Eq '^[[:space:]]*ghcr\.io/autonox-ai/' "$MANIFEST"; then
  echo "Logging into GHCR"
  if [[ -n "${GHCR_USER:-}" && -n "${GHCR_TOKEN:-}" ]]; then
    printf '%s' "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin >/dev/null
  elif command -v gh >/dev/null 2>&1; then
    gh auth token | docker login ghcr.io -u "$(gh api user --jq .login)" --password-stdin >/dev/null
  else
    echo "GHCR auth needed for private AutoNox images." >&2
    echo "Run 'gh auth login', set GHCR_USER/GHCR_TOKEN, or set GHCR_LOGIN=0 if Docker is already logged in." >&2
    exit 1
  fi
fi

# Previous lock, if any: lets an unchanged image skip the expensive re-save.
declare -A prev_id=()
if [[ -f "$LOCK" ]]; then
  while IFS=$'\t' read -r l_image l_id _l_digest _l_tar; do
    [[ -z "$l_image" || "$l_image" == \#* ]] && continue
    prev_id["$l_image"]="$l_id"
  done < "$LOCK"
fi

entries=()   # image \t id \t digest \t tar
expected=()  # tar basenames this manifest calls for

while IFS= read -r line; do
  # Strip comments and surrounding whitespace.
  image="${line%%#*}"
  image="${image#"${image%%[![:space:]]*}"}"
  image="${image%"${image##*[![:space:]]}"}"
  [[ -z "$image" ]] && continue

  # Slug: replace / and : with _ for a filesystem-safe name.
  slug="${image//\//_}"
  slug="${slug//:/_}"
  tar_name="${slug}.tar"
  out="${OUT_DIR}/${tar_name}"
  tmp="${out}.tmp"
  expected+=( "$tar_name" )

  # Always pull. A tag can be repointed upstream, so the tar's existence says
  # nothing about whether it holds the image the manifest currently resolves to.
  echo "pull  $image  ($PLATFORM)"
  docker pull --platform="$PLATFORM" "$image" >/dev/null

  id="$(docker image inspect --platform="$PLATFORM" --format '{{.Id}}' "$image")"
  digest="$(docker image inspect --platform="$PLATFORM" \
    --format '{{if .RepoDigests}}{{index .RepoDigests 0}}{{else}}-{{end}}' "$image")"

  if [[ -f "$out" && "${prev_id[$image]:-}" == "$id" ]]; then
    echo "keep  $image (unchanged: $tar_name)"
  else
    if [[ -f "$out" ]]; then
      echo "stale $image (tag now resolves to $id — re-saving)"
    fi
    echo "save  $image -> $out"
    docker save --platform="$PLATFORM" -o "$tmp" "$image"
    mv "$tmp" "$out"
  fi

  entries+=( "${image}"$'\t'"${id}"$'\t'"${digest}"$'\t'"${tar_name}" )
done < "$MANIFEST"

if [[ ${#entries[@]} -eq 0 ]]; then
  echo "manifest lists no images: $MANIFEST" >&2
  exit 1
fi

# Write the lock atomically so an interrupted run never leaves a bundle
# claiming images it did not save.
{
  echo "# AutoNox air-gap bundle lock — generated by pull-and-save.sh"
  echo "# Consumed by load.sh. Do not edit by hand."
  echo "# platform: ${PLATFORM}"
  echo "# generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# <image ref>\t<image id>\t<registry digest>\t<tar file>"
  printf '%s\n' "${entries[@]}"
} > "${LOCK}.tmp"
mv "${LOCK}.tmp" "$LOCK"

echo
echo "Done. Bundle is in: $OUT_DIR (${#entries[@]} images, lock: $(basename "$LOCK"))"

# Tars from an older manifest are inert — load.sh only reads the lock — but they
# still cost transfer bytes, so say so rather than shipping them silently.
shopt -s nullglob
stale=()
for tar in "$OUT_DIR"/*.tar; do
  name="$(basename "$tar")"
  keep=0
  for want in "${expected[@]}"; do
    [[ "$name" == "$want" ]] && { keep=1; break; }
  done
  (( keep )) || stale+=( "$tar" )
done

if [[ ${#stale[@]} -gt 0 ]]; then
  echo
  echo "WARNING: ${#stale[@]} tar(s) in $OUT_DIR are not in the current manifest."
  printf '  %s\n' "${stale[@]}"
  echo "They will not be loaded. Remove them before transfer:"
  printf '  rm %q\n' "${stale[@]}"
fi
