apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: pgvector
  app.kubernetes.io/part-of: autonox

resources:
  - configmap-initdb.yaml
  - service.yaml
  - statefulset.yaml
  - job-smoke-test.yaml
  # NOTE: Secrets are NOT shipped by default. See README.md for required secret.
